### ISSUE TITLE
SDE Frontend QG 4 checks (Release 3.2)

### ISSUE THREAD

**Issue by almadigabor** [eclipse-tractusx/managed-simple-data-exchanger-frontend#20]
# The main issue can be found [here](https://github.com/eclipse-tractusx/managed-simple-data-exchanger/issues/6). This issue is just to check specific content of the frontend repository.

### Please keep this issue open until QG 4 is concluded!

Product Name: Managed Simple Data Exchanger Frontend
Product Owner: Mehran Roshandel
Dev SPOC: Aditya Gajbhiye
App Version:  `2.0.8`

### Check of Tractus-X Release Guidelines

This QG 4 Check is depending on the mandatory information from our current [Release Guidelines](https://eclipse-tractusx.github.io/docs/release).

#### TRG 1 Documentation
- [x] #22
- [x] [TRG 1.02](https://eclipse-tractusx.github.io/docs/release/trg-1/trg-1-2) appropriate `INSTALL.md` https://github.com/eclipse-tractusx/managed-simple-data-exchanger-frontend/issues/22
- [x] [TRG 1.03](https://eclipse-tractusx.github.io/docs/release/trg-1/trg-1-3) appropriate `CHANGELOG.md`
#### TRG 2 Git
- [x] [TRG 2.01](https://eclipse-tractusx.github.io/docs/release/trg-2/trg-2-1) default branch is named `main`
- [x] [TRG 2.03](https://eclipse-tractusx.github.io/docs/release/trg-2/trg-2-3) repository structure
  <details>
  <summary>Checks within TRG 2.03</summary>

  - [x] TRG 2.03 `/docs` directory contains detailed product related documentation for the Tractus-X product 
  - [x] TRG 2.03 `/charts` directory contains the Helm chart for the Tractus-X product IF available
  - [x] TRG 2.03 `AUTHORS.md` file (optional) (TRG 2.03) https://github.com/eclipse-tractusx/managed-simple-data-exchanger-frontend/issues/23
  - [x] TRG 2.03 `CODE_OF_CONDUCT.md` file (TRG 2.03) https://github.com/eclipse-tractusx/managed-simple-data-exchanger-frontend/issues/24
  - [x] TRG 2.03 `CONTRIBUTING.md` file (TRG 2.03)
  - [x] TRG 2.03 `DEPENDENCIES` file(s) with up to date content (Dash tool generated) (TRG 2.03)
  - [x] TRG 2.03 `LICENSE` file (TRG 2.03)
  - [x] TRG 2.03 `NOTICE.md` file (TRG 2.03)
  - [x] TRG 2.03 `SECURITY.md` file (TRG 2.03)
  </details>

- [x] [TRG 2.04](https://eclipse-tractusx.github.io/docs/release/trg-2/trg-2-4) Leading product repository
  <details>
  <summary>Checks within TRG 2.04</summary>
  
  - [x] TRG 2.04 repository name must be _productname_ without prefix or suffix
  - [x] TRG 2.04 should contain the release
  - [x] TRG 2.04 references/urls to the product's other repositories https://github.com/eclipse-tractusx/managed-simple-data-exchanger-frontend/issues/22
  - [x] TRG 2.04 might contain product helm chart(s)
  - [x] TRG 2.04 README.md: contains the urls for the underlying applications
  </details>

- [x] [TRG 2.05](https://eclipse-tractusx.github.io/docs/release/trg-2/trg-2-5) `.tractusx` metafile in a proper format
#### TRG 3 Kubernetes
- [x] [TRG 3.02](https://eclipse-tractusx.github.io/docs/release/trg-3/trg-3-2) PersistentVolume and PersistentVolumeClaim is used when needed
#### TRG 4 Container
- [x] #25
- [x] [TRG 4.02](https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-2) top level `README.md` file, that contains information about the used base image  https://github.com/eclipse-tractusx/managed-simple-data-exchanger-frontend/issues/22
- [x] [TRG 4.03](https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-3) Image has `USER` command and Non Root Container
  <details>
  <summary>Checks within TRG 4.03</summary>
  
  - [x] TRG 4.03 `deployment.yaml` has `runAsUser` and `allowPrivilegeEscalation: false` properly set
  </details>

- [x] [TRG 4.05](https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-05) released image must be place `DockerHub` as mandatory container registry; remove `GHCR` references 
- [x] [TRG 4.06](https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-06) Notice File for `DockerHub` has all necessary information https://github.com/eclipse-tractusx/managed-simple-data-exchanger-frontend/issues/22
  <details>
  <summary>Checks within TRG 4.06</summary>

  - [x] TRG 4.06 Link to the source of your base image (Container registry and GitHub if available)
  - [x] TRG 4.06 Link to your product image on `DockerHub`
  - [x] TRG 4.06 Link to your repository on `GitHub`
  - [x] TRG 4.06 Direct link to the Dockerfile used to build your image
  - [x] TRG 4.06 Link to LICENCE file in your repo as `Project License` (make clear, that this is the PROJECT licence, not an image license
  </details>

#### TRG 6 Released Helm Chart 
- [x] [TRG 6.01](https://eclipse-tractusx.github.io/docs/release/trg-6/trg-6-1) Released Helm Chart 
#### TRG 7 Open Source Governance
- [x] #26
- [x] [TRG 7.02](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) License and copyright header  https://github.com/eclipse-tractusx/managed-simple-data-exchanger-frontend/issues/21
- [x] [TRG 7.03](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-03) IP checks for project content 
- [x] [TRG 7.04](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-04) IP checks for 3rd party content
  <details>
  <summary>Checks within TRG 7.04</summary>

  - [x] TRG 7.04 DEPENDENCIES file is up-to-date and reflects the current use of the 3rd party content
  - [x] TRG 7.04 all libraries listed there should have the status "approved"
  - [x] TRG 7.04 no libraries with status "rejected"
  - [x] TRG 7.04 for libraries with status "restricted", the according IP issues must be present (issue number in the source column)
  </details>
- [x] [TRG 7.05](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-05) Legal information for distributions
- [x] [TRG 7.06](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-06) Legal information for end user content https://github.com/eclipse-tractusx/managed-simple-data-exchanger-frontend/issues/28
- [x] [TRG 7.07](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-07) Legal notice for documentation https://github.com/eclipse-tractusx/managed-simple-data-exchanger-frontend/issues/27

**Comment by almadigabor** [comment]
Frontend tasks are done, closing this issue.
